<<<<<<< HEAD
# Generated by Django 4.2.21 on 2025-05-21 08:35

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.2.1 on 2025-06-05 07:56

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> bee78e8f8b34bfc8e75e08ac77a3a7df56667643


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('url', models.URLField(max_length=500)),
=======
                ('group_name', models.CharField(default='Unnamed Group', max_length=255)),
>>>>>>> bee78e8f8b34bfc8e75e08ac77a3a7df56667643
            ],
        ),
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('page_name', models.CharField(max_length=255)),
                ('page_url', models.URLField()),
                ('page_username', models.CharField(blank=True, max_length=255, null=True)),
                ('page_category', models.CharField(blank=True, max_length=255, null=True)),
                ('page_website', models.URLField(blank=True, null=True)),
                ('page_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('page_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('page_address', models.TextField(blank=True, null=True)),
                ('page_number', models.CharField(blank=True, max_length=255, null=True)),
                ('page_country', models.CharField(blank=True, max_length=255, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('page_followers', models.CharField(blank=True, max_length=255, null=True)),
                ('page_likes', models.CharField(blank=True, max_length=255, null=True)),
                ('page_talking_count', models.CharField(blank=True, max_length=255, null=True)),
                ('page_engagement', models.CharField(blank=True, max_length=255, null=True)),
                ('page_index', models.CharField(blank=True, max_length=255, null=True)),
                ('page_post_per_day', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PageInfo.pagegroup')),
=======
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('lemon8', 'Lemon8'), ('youtube', 'Youtube')], default='facebook', max_length=20)),
                ('page_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_url', models.URLField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.URLField(blank=True, max_length=500, null=True)),
                ('page_username', models.CharField(blank=True, max_length=255, null=True)),
                ('page_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_business_page', models.BooleanField(blank=True, null=True)),
                ('page_followers', models.CharField(blank=True, max_length=100, null=True)),
                ('page_likes', models.CharField(blank=True, max_length=100, null=True)),
                ('page_followers_count', models.IntegerField(blank=True, null=True)),
                ('page_likes_count', models.CharField(blank=True, max_length=100, null=True)),
                ('page_talking_count', models.CharField(blank=True, max_length=100, null=True)),
                ('page_were_here_count', models.CharField(blank=True, max_length=100, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('page_category', models.CharField(blank=True, max_length=255, null=True)),
                ('page_address', models.CharField(blank=True, max_length=500, null=True)),
                ('page_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('page_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('page_website', models.URLField(blank=True, max_length=500, null=True)),
                ('following_count', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('post_count', models.IntegerField(blank=True, null=True)),
                ('page_join_date', models.CharField(blank=True, max_length=100, null=True)),
                ('page_videos_count', models.BigIntegerField(blank=True, null=True)),
                ('page_total_views', models.BigIntegerField(blank=True, null=True)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='PageInfo.pagegroup')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('post_timestamp_dt', models.DateTimeField()),
                ('post_timestamp_text', models.TextField()),
                ('post_content', models.TextField()),
                ('post_imgs', models.JSONField(blank=True, default=list, null=True)),
                ('reactions', models.JSONField(blank=True, default=dict, null=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_posts', to='PageInfo.pageinfo')),
>>>>>>> bee78e8f8b34bfc8e75e08ac77a3a7df56667643
            ],
        ),
    ]
